### ISSUE TITLE
  Error: throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +

### ISSUE THREAD

**Issue by honeyfairy** [deyvissonbrenoveras/ovpnconfig.com.br#9]
I did git clone, then docker build, then docker up. When starting this is the issue:

`[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
[nodemon] forking
[nodemon] child pid: 33
[nodemon] watching 100 files
/usr/src/app/node_modules/mongoose/lib/connection.js:694
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (/usr/src/app/node_modules/mongoose/lib/connection.js:694:11)
    at /usr/src/app/node_modules/mongoose/lib/index.js:351:10
    at promiseOrCallback (/usr/src/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:10:12)
    at Mongoose._promiseOrCallback (/usr/src/app/node_modules/mongoose/lib/index.js:1149:10)
    at Mongoose.connect (/usr/src/app/node_modules/mongoose/lib/index.js:350:20)
    at Object.<anonymous> (/usr/src/app/app.js:15:10)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...
`

**Comment by JLENF** [comment]
you need create a .env file.
just copy existing .env.template do .env and configure.

the only line I changed in my code to work is: 
MONGODB_STRING="mongodb://mongo:27017"
